const getters = {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  uid: state => state.user.uid,
  orgName: state => state.user.orgName,
  id: state => state.user.id,
  caseNo: state => state.user.caseNo,
  webName: state => state.user.webName,
  instanceNo: state => state.user.instanceNo,
  evidenceNo: state => state.user.evidenceNo,
  groupName: state => state.user.groupName,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  // groupId: state => state.user.groupId,
  introduction: state => state.user.introduction,
  status: state => state.user.status,
  roles: state => state.user.roles,
  setting: state => state.user.setting,
  permission_routers: state => state.permission.routers,
  addRouters: state => state.permission.addRouters,
  errorLogs: state => state.errorLog.logs
}
export default getters
